name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: compiling and testing
      run: |
        for d in */ ; do
        cd "$d"
        make
        cd ..
        done
