name: C1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: go to lab 1 and build
      working-directory: ./lab 1
      run: make 
    - name: go to lab 2.1 and build
      working-directory: ./lab 2/lab 2.1
      run: make
    - name: go to lab 2.2
      working-directory: ./lab 2/lab 2.2
      run: make
      
      
      
