name: C1

on:
  push:
    branches: [ master ]
    paths:
      - 'lab 1/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'lab 1/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: go to lab 1 and build
      working-directory: ./lab 1
      run: make 
