name: LAB3

on:
  push:
    branches: [ main ]
    paths:
      - 'lab 3/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'lab 3/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: makeLab
      working-directory: ./lab 3
      run: make