name: C1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: go to task 1 and build
      working-directory: ./lab 4/task 1
      run: make
    - name: go to task 2
      working-directory: ./lab 4/task 2
      run: make
      
      
      
